--------------------------------------------------------
--  DDL for Table EBA_DEMO_LOAD_EMP_ERR$
--------------------------------------------------------

  CREATE TABLE "EBA_DEMO_LOAD_EMP_ERR$" ("ORA_ERR_NUMBER$" NUMBER, "ORA_ERR_MESG$" VARCHAR2(2000) COLLATE "USING_NLS_COMP", "ORA_ERR_ROWID$" UROWID (4000), "ORA_ERR_OPTYP$" VARCHAR2(2) COLLATE "USING_NLS_COMP", "ORA_ERR_TAG$" VARCHAR2(2000) COLLATE "USING_NLS_COMP", "EMPNO" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "ENAME" VARCHAR2(32767) COLLATE "USING_NLS_COMP", "JOB" VARCHAR2(32767) COLLATE "USING_NLS_COMP", "MGR" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "HIREDATE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "SAL" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "COMM" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "DEPTNO" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "CREATED" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "LAST_UPDATED" VARCHAR2(4000) COLLATE "USING_NLS_COMP")  DEFAULT COLLATION "USING_NLS_COMP" 

   COMMENT ON TABLE "EBA_DEMO_LOAD_EMP_ERR$"  IS 'DML Error Logging table for "EBA_DEMO_LOAD_EMP"'
