--------------------------------------------------------
--  Constraints for Table EBA_DEMO_FILE_PROJECTS
--------------------------------------------------------

  ALTER TABLE "EBA_DEMO_FILE_PROJECTS" MODIFY ("PROJECT" NOT NULL ENABLE)
  ALTER TABLE "EBA_DEMO_FILE_PROJECTS" MODIFY ("TASK_NAME" NOT NULL ENABLE)
  ALTER TABLE "EBA_DEMO_FILE_PROJECTS" MODIFY ("START_DATE" NOT NULL ENABLE)
  ALTER TABLE "EBA_DEMO_FILE_PROJECTS" MODIFY ("END_DATE" NOT NULL ENABLE)
  ALTER TABLE "EBA_DEMO_FILE_PROJECTS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "EBA_DEMO_FILE_PROJECTS" ADD CONSTRAINT "EBA_DEMO_FILE_PROJECTS_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
