--------------------------------------------------------
--  DDL for Table EBA_DEMO_FILES
--------------------------------------------------------

  CREATE TABLE "EBA_DEMO_FILES" ("ID" NUMBER, "ROW_VERSION_NUMBER" NUMBER, "PROJECT_ID" NUMBER, "FILENAME" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "FILE_MIMETYPE" VARCHAR2(512) COLLATE "USING_NLS_COMP", "FILE_CHARSET" VARCHAR2(512) COLLATE "USING_NLS_COMP", "FILE_BLOB" BLOB, "FILE_COMMENTS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "TAGS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "CREATED" TIMESTAMP (6), "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", "UPDATED" TIMESTAMP (6), "UPDATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP")  DEFAULT COLLATION "USING_NLS_COMP"
