--------------------------------------------------------
--  DDL for Table EBA_DEMO_FILE_PROJECTS
--------------------------------------------------------

  CREATE TABLE "EBA_DEMO_FILE_PROJECTS" ("ID" NUMBER, "ROW_VERSION_NUMBER" NUMBER, "PROJECT" VARCHAR2(30) COLLATE "USING_NLS_COMP", "TASK_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", "START_DATE" DATE, "END_DATE" DATE, "STATUS" VARCHAR2(30) COLLATE "USING_NLS_COMP", "ASSIGNED_TO" VARCHAR2(30) COLLATE "USING_NLS_COMP", "COST" NUMBER, "BUDGET" NUMBER, "CREATED_ON" TIMESTAMP (6), "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", "BROWSER_ENV" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "ICON_NAME" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "ICON_COMMENTS" VARCHAR2(4000) COLLATE "USING_NLS_COMP", "ICON_BLOB" BLOB, "ICON_MIMETYPE" VARCHAR2(512) COLLATE "USING_NLS_COMP", "ICON_CHARSET" VARCHAR2(512) COLLATE "USING_NLS_COMP", "ICON_LAST_UPDATED" TIMESTAMP (6))  DEFAULT COLLATION "USING_NLS_COMP"
